
// src/app/glossary/hash-rate/page.tsx
'use client';

import { useState } from 'react';
import { Footer } from '@/components/landing/Footer';
import { Header } from '@/components/landing/Header';
import { Card, CardContent } from '@/components/ui/card';
import { ShieldCheck, Cpu } from 'lucide-react';

import { PrivacyPolicyModal } from '@/components/landing/PrivacyPolicyModal';
import { TermsOfServiceModal } from '@/components/landing/TermsOfServiceModal';
import Link from 'next/link';
import { GlossaryPageWrapper } from '@/components/glossary/GlossaryPageWrapper';

export default function HashRateGlossaryPage() {
  const [activeModal, setActiveModal] = useState<'privacy' | 'terms' | null>(null);

  const openPrivacyModal = () => setActiveModal('privacy');
  const openTermsModal = () => setActiveModal('terms');
  const closeModal = () => setActiveModal(null);
  const relatedTerms = [
    { slug: 'mining', title: 'Mining', description: 'Bitcoin concept' },
    { slug: 'block', title: 'Block', description: 'Transaction container' },
    { slug: 'double-spend', title: 'Double Spend', description: 'Attack prevention' }
  ];


  return (
    <div className="flex flex-col min-h-dvh bg-background">
      <Header />
      <GlossaryPageWrapper termSlug="hash-rate" relatedTerms={relatedTerms}>
            <h1 itemProp="headline" className="text-4xl font-bold mb-4 text-foreground">
              What Is Hash Rate?
            </h1>
            <p itemProp="description" className="text-lg text-muted-foreground font-normal">
              The hash rate is a crucial measure of the Bitcoin network's health and security. It represents the total combined computational power that miners are dedicating to solving the next block and processing transactions.
            </p>

            <Card className="my-6 bg-[#1a1a1a] border-none shadow-xl hover:shadow-2xl">
              <CardContent className="p-4">
                 <h3 className="text-xl font-bold flex items-center mb-2">
                    <Cpu className="mr-2 h-6 w-6 text-primary" />
                    A Measure of Power
                </h3>
                <p className="text-muted-foreground mt-2 font-normal">
                   Think of it as the network's total horsepower. It's measured in hashes per second (H/s), with modern values often in the exahashes (quintillions of hashes) per second.
                </p>
              </CardContent>
            </Card>

            <div className="mt-8 grid md:grid-cols-2 gap-8">
                <div>
                    <h3 className="text-xl font-bold flex items-center">
                        <ShieldCheck className="mr-2 h-6 w-6 text-primary" />
                        Network Security
                    </h3>
                    <p className="text-muted-foreground mt-2 font-normal">
                     A higher hash rate makes the network more secure. It means an attacker would need an immense amount of computational power to try and reverse transactions, making such an attack prohibitively expensive.
                    </p>
                </div>
                <div>
                    <h3 className="text-xl font-bold flex items-center">
                        <Cpu className="mr-2 h-6 w-6 text-primary" />
                        The Role of Mining
                    </h3>
                    <p className="text-muted-foreground mt-2 font-normal">
                     The hash rate is generated by miners all over the world competing in the <Link href="/glossary/mining" className="text-primary hover:underline">mining</Link> process. The collective effort of these miners is what secures the blockchain.
                    </p>
                </div>
            </div>
            
            <h2 className="text-3xl font-bold mt-12 mb-4 text-foreground">
              An Indicator of Health
            </h2>
            <p className="text-muted-foreground font-normal">
             A consistently high or rising hash rate is generally seen as a sign of a healthy and robust Bitcoin network, indicating that miners are confident and willing to invest significant resources in its operation.
            </p>
          </GlossaryPageWrapper>
      <Footer onPrivacyClick={openPrivacyModal} onTermsClick={openTermsModal} />
      <PrivacyPolicyModal isOpen={activeModal === 'privacy'} onOpenChange={closeModal} />
      <TermsOfServiceModal 
        isOpen={activeModal === 'terms'} 
        onOpenChange={closeModal}
        onPrivacyClick={openPrivacyModal} 
      />
    </div>
  );
}
